version: "3.9"
services:
  frontend:
    build:
      context: ./
      dockerfile: ./frontend/Dockerfile
    restart: always
    ports:
      - 80:80
    networks:
      - public

  publicapi:
    build:
      context: ./
      dockerfile: ./public-api/Dockerfile
    ports:
      - 3333:3333
    networks:
      - public

  mentor:
    build:
      context: ./mentor/
    ports:
      - 8000:8000
    networks:
      - public

networks:
  public:
