version: "3.9"
services:
  frontend:
    build:
      context: ./frontend/
    restart: always
    ports:
      - 80:80

  publicapi:
    build:
      context: ./public-api/
    ports:
      - 3333:3333

  mentor:
    build:
      context: ./mentor/
    ports:
      - 8000:8000