version: "3.9"
services:
  mentor:
    build:
      context: ./mentor/
    ports:
      - 8000:8000

  mongodb:
    image: mongo:5.0.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=aWEsomeDatabase
    expose:
      - 27017
    volumes:
      - ~/mongodb/data:/data/db
      - ~/mongodb/configdb:/data/configdb
    restart: unless-stopped

  mongo-seed:
    build: ./mongo-seed
    depends_on:
      - mongodb

  publicapi:
    environment:
      - FRONTEND_URL=${HOST_URL}
    build:
      context: ./public-api/
    depends_on:
      - mongo-seed
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.backend.entrypoints=web"
    - "traefik.http.routers.backend.rule=HostRegexp(`{catchall:.*}`) && PathPrefix(`/api`)"
    - "traefik.http.services.backend.loadbalancer.server.port=3333"

  frontend:
    environment:
      - PUBLIC_API_URL=${HOST_URL}/api
    build:
      context: ./frontend/
    restart: always
    depends_on:
      - publicapi
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.frontend.entrypoints=web"
    - "traefik.http.routers.frontend.rule=HostRegexp(`{catchall:.*}`)"

  reverse-proxy:
    image: "traefik:v2.9"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

