version: "3.9"
services:

  mentor:
    build:
      context: ./mentor/
    ports:
      - 8000:8000
    networks:
      - public

  mongodb:
    image: mongo:5.0.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=aWEsomeDatabase
    expose:
      - 27017
    volumes:
      - ./mongodb/data:/data/db
      - ./mongodb/configdb:/data/configdb
    networks:
      - public
    restart: unless-stopped

  mongo-seed:
    build: ./mongo-seed
    depends_on:
      - mongodb
    networks:
      - public

  publicapi:
    build:
      context: ./public-api/
    ports:
      - 3333:3333
    depends_on:
      - mongo-seed
    networks:
      - public

  frontend:
    build:
      context: ./frontend/
    restart: always
    ports:
      - 80:80
    depends_on:
      - publicapi
    networks:
      - public

networks:
  public:
