name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Pull docker down and put it up
      run: |
        docker compose down
        docker compose up --build -d