name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Build frontend
      run: |
        docker compose down
        docker compose up --build -d