name: Frontend

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  format:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Check formatting frontend
      run: |
        cd frontend
        yarn install --frozen-lockfile
        yarn prettier -c src/
  lint:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Lint frontend
      run: |
        cd frontend
        yarn install --frozen-lockfile
        yarn eslint src/
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Build frontend
      run: |
        cd frontend
        yarn install --frozen-lockfile
        yarn build
