name: Frontend

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
    - name: Check formatting frontend
      run: |
        cd frontend
        yarn install --frozen-lockfile
        yarn prettier -c src/
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
    - name: Lint frontend
      run: |
        cd frontend
        yarn install --frozen-lockfile
        yarn eslint src/
  build:
    runs-on: ubunut-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
    - name: Build frontend
      run: |
        cd frontend
        yarn install --frozen-lockfile
        yarn build