name: Frontend

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  format:
    runs-on: self-hosted
    container: node:16
    steps:
    - uses: actions/checkout@v3
    - name: Check formatting frontend
      run: |
        cd frontend
        yarn install --frozen-lockfile
        yarn prettier -c src/
  lint:
    runs-on: self-hosted
    container: node:16
    steps:
    - uses: actions/checkout@v3
    - name: Lint frontend
      run: |
        cd frontend
        yarn install --frozen-lockfile
        yarn eslint src/
  build:
    runs-on: self-hosted
    container: node:16
    steps:
    - uses: actions/checkout@v3
    - name: Build frontend
      run: |
        cd frontend
        yarn install --frozen-lockfile
        yarn build
