name: Github Actions Runner

on: push

jobs:
  info:
    runs-on: self-hosted
    steps:
    - name: Get some info
      run: |
        whoami
        pwd
  yarn:
    runs-on: self-hosted
    steps:
    - name: Check if yarn is installed
      run: |
        yarn --version
  docker:
    runs-on: self-hosted
    steps:
    - name: Docker info
      run: |
        docker version --format '{{.Server.APIVersion}}'
