name: Mentor

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  format:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Create and enter venv
      run: |
        cd mentor
        python -m venv venv
        source venv/bin/activate
    - name: Format Mentor
      run: |
        pip install black
        black server.py engine
    - name: Deactivate venv
      run: |
        deactivate
  lint:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Create and enter venv
      run: |
        cd mentor
        python -m venv venv
        source venv/bin/activate
    - name: Lint Mentor
      run: |
        cd mentor
        pip install flake8
        flake8 server.py engine
    - name: Deactivate venv
      run: |
        deactivate