name: Mentor

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  format:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - uses: psf/black@stable
      with:
        options: "--check --verbose"
        src: "."
        version: "22.6.0"
  lint:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9' 
    - name: Lint Mentor
      run: |
        cd mentor
        pip install flake8
        flake8 server.py engine