name: PublicAPI - Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 16
      uses: actions/setup-node@v1
      with:
        node-version: 16

    - name: Build PublicAPI
      run: |
        cd frontend
        yarn install --frozen-lockfile
        yarn build
    - name: Test PublicAPI
      run: |
        cd frontend
        yarn test
